//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:5.0.17
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FullStackCodeGenerator {
    using SimpleCodeGenerator;
    using System;
    
    
    public partial class index_html_tt_fccc6d1b_51b9_4f59_bcac_4179107740f4 : BaseTemplate<ProjectTemplate> {
        
        
        #line 15 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Clientside\public\index.html.tt"

    public override string RelativeFilePath => $"Clientside/public/index.html";

        #line default
        #line hidden
        
        
        public override string TransformText() {
            this.GenerationEnvironment = null;
            
            #line 3 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Clientside\public\index.html.tt"
            this.Write("<!DOCTYPE html>\r\n<html lang=\"en\">\r\n  <head>\r\n    <meta charset=\"utf-8\" />\r\n    <t" +
                    "itle>React App</title>\r\n  </head>\r\n  <body>\r\n    <noscript>You need to enable Ja" +
                    "vaScript to run this app.</noscript>\r\n    <div id=\"root\"></div>\r\n  </body>\r\n</ht" +
                    "ml>\r\n\r\n");
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        public override void Initialize() {
            base.Initialize();
        }
    }
}
