//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:5.0.17
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FullStackCodeGenerator {
    using SimpleCodeGenerator;
    using System;
    
    
    public partial class _Entity_ts_tt_38c146db_2404_4d22_bb4f_4e91d74ec63c : BaseTemplate<EntityTemplate> {
        
        
        #line 16 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Serverside\src\Models\_Entity.ts.tt"

    public override string RelativeFilePath => $"Serverside/src/Models/{Model.Entity.Name}.ts";

        #line default
        #line hidden
        
        
        public override string TransformText() {
            this.GenerationEnvironment = null;
            
            #line 3 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Serverside\src\Models\_Entity.ts.tt"
            this.Write("import { BaseEntity } from \"./BaseEntity\";\r\n\r\nexport class ");
            
            #line default
            #line hidden
            
            #line 5 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Serverside\src\Models\_Entity.ts.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Model.Entity.Name ));
            
            #line default
            #line hidden
            
            #line 5 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Serverside\src\Models\_Entity.ts.tt"
            this.Write(" extends BaseEntity {\r\n");
            
            #line default
            #line hidden
            
            #line 6 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Serverside\src\Models\_Entity.ts.tt"

	foreach (var attribute in Model.Entity.Attributes)
	{

            
            #line default
            #line hidden
            
            #line 10 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Serverside\src\Models\_Entity.ts.tt"
            this.Write("\t");
            
            #line default
            #line hidden
            
            #line 10 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Serverside\src\Models\_Entity.ts.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( attribute.Name ));
            
            #line default
            #line hidden
            
            #line 10 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Serverside\src\Models\_Entity.ts.tt"
            this.Write("?: ");
            
            #line default
            #line hidden
            
            #line 10 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Serverside\src\Models\_Entity.ts.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( attribute.Type ));
            
            #line default
            #line hidden
            
            #line 10 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Serverside\src\Models\_Entity.ts.tt"
            this.Write(";\r\n");
            
            #line default
            #line hidden
            
            #line 11 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Serverside\src\Models\_Entity.ts.tt"

	}

            
            #line default
            #line hidden
            
            #line 14 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Serverside\src\Models\_Entity.ts.tt"
            this.Write("}\r\n\r\n");
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        public override void Initialize() {
            base.Initialize();
        }
    }
}
