//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:5.0.17
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FullStackCodeGenerator {
    using SimpleCodeGenerator;
    using System;
    
    
    public partial class App_tsx_tt_86eecae8_bc80_4f55_ab40_777ad3cc0f87 : BaseTemplate<ProjectTemplate> {
        
        
        #line 83 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Clientside\src\App.tsx.tt"

    public override string RelativeFilePath => $"Clientside/src/App.tsx";

        #line default
        #line hidden
        
        
        public override string TransformText() {
            this.GenerationEnvironment = null;
            
            #line 3 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Clientside\src\App.tsx.tt"
            this.Write("import React from \'react\';\r\nimport styled from \'styled-components\'\r\nimport {\r\n  B" +
                    "rowserRouter as Router,\r\n  Route,\r\n  Link,\r\n  Routes\r\n} from \"react-router-dom\";" +
                    "\r\n");
            
            #line default
            #line hidden
            
            #line 11 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Clientside\src\App.tsx.tt"

    foreach (var entity in Model.Project.Entities)
    {

            
            #line default
            #line hidden
            
            #line 15 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Clientside\src\App.tsx.tt"
            this.Write("import ");
            
            #line default
            #line hidden
            
            #line 15 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Clientside\src\App.tsx.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.Name ));
            
            #line default
            #line hidden
            
            #line 15 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Clientside\src\App.tsx.tt"
            this.Write("Page from \'./Views/Pages/");
            
            #line default
            #line hidden
            
            #line 15 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Clientside\src\App.tsx.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.Name ));
            
            #line default
            #line hidden
            
            #line 15 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Clientside\src\App.tsx.tt"
            this.Write("Page\';\r\n");
            
            #line default
            #line hidden
            
            #line 16 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Clientside\src\App.tsx.tt"

    }

            
            #line default
            #line hidden
            
            #line 19 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Clientside\src\App.tsx.tt"
            this.Write(@"
const AppWrapper = styled.div`
font-family: sans-serif;
.nav {
  background: black;
  display: flex;
  padding: 1rem;
  a {
    color: white;
    margin: 0 2rem;
  }
}
.body {
  padding: 3rem;
}
.attributes {
  display: flex;
  flex-direction: column;
  width: 20rem;
  .attribute {
    display: flex;
    flex-direction: column;
    margin-bottom: 0.2rem;
  }
}
button {
  background: black;
  color: white;
}
`

function App() {
  return (
    <AppWrapper>
      <Router>
        <div className='nav'>
");
            
            #line default
            #line hidden
            
            #line 55 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Clientside\src\App.tsx.tt"

    foreach (var entity in Model.Project.Entities)
    {

            
            #line default
            #line hidden
            
            #line 59 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Clientside\src\App.tsx.tt"
            this.Write("          <Link to=\"");
            
            #line default
            #line hidden
            
            #line 59 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Clientside\src\App.tsx.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.Name ));
            
            #line default
            #line hidden
            
            #line 59 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Clientside\src\App.tsx.tt"
            this.Write("\">");
            
            #line default
            #line hidden
            
            #line 59 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Clientside\src\App.tsx.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.Name ));
            
            #line default
            #line hidden
            
            #line 59 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Clientside\src\App.tsx.tt"
            this.Write("</Link>\r\n");
            
            #line default
            #line hidden
            
            #line 60 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Clientside\src\App.tsx.tt"

    }

            
            #line default
            #line hidden
            
            #line 63 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Clientside\src\App.tsx.tt"
            this.Write("        </div>\r\n        <div className=\'body\'>\r\n          <Routes>\r\n");
            
            #line default
            #line hidden
            
            #line 66 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Clientside\src\App.tsx.tt"

    foreach (var entity in Model.Project.Entities)
    {

            
            #line default
            #line hidden
            
            #line 70 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Clientside\src\App.tsx.tt"
            this.Write("            <Route path=\"/");
            
            #line default
            #line hidden
            
            #line 70 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Clientside\src\App.tsx.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.Name ));
            
            #line default
            #line hidden
            
            #line 70 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Clientside\src\App.tsx.tt"
            this.Write("\" element={<");
            
            #line default
            #line hidden
            
            #line 70 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Clientside\src\App.tsx.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.Name ));
            
            #line default
            #line hidden
            
            #line 70 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Clientside\src\App.tsx.tt"
            this.Write("Page />} />\r\n");
            
            #line default
            #line hidden
            
            #line 71 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Clientside\src\App.tsx.tt"

    }

            
            #line default
            #line hidden
            
            #line 74 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Clientside\src\App.tsx.tt"
            this.Write("          </Routes>\r\n        </div>\r\n      </Router>\r\n    </AppWrapper>\r\n  );\r\n}\r" +
                    "\n\r\nexport default App;\r\n\r\n");
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        public override void Initialize() {
            base.Initialize();
        }
    }
}
