//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:5.0.17
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FullStackCodeGenerator {
    using SimpleCodeGenerator;
    using System;
    
    
    public partial class package_json_tt_d3cc4c3d_afa1_47fb_810a_dcae19ff2e64 : BaseTemplate<ProjectTemplate> {
        
        
        #line 77 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Serverside\package.json.tt"

    public override string RelativeFilePath => $"Serverside/package.json";

        #line default
        #line hidden
        
        
        public override string TransformText() {
            this.GenerationEnvironment = null;
            
            #line 3 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Serverside\package.json.tt"
            this.Write("{\r\n  \"name\": \"");
            
            #line default
            #line hidden
            
            #line 4 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Serverside\package.json.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Model.Project.Name ));
            
            #line default
            #line hidden
            
            #line 4 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Serverside\package.json.tt"
            this.Write("\",\r\n  \"version\": \"0.0.1\",\r\n  \"description\": \"\",\r\n  \"author\": \"\",\r\n  \"private\": tr" +
                    "ue,\r\n  \"license\": \"UNLICENSED\",\r\n  \"scripts\": {\r\n    \"prebuild\": \"rimraf dist\",\r" +
                    "\n    \"build\": \"nest build\",\r\n    \"format\": \"prettier --write \\\"src/**/*.ts\\\" \\\"t" +
                    "est/**/*.ts\\\"\",\r\n    \"start\": \"nest start\",\r\n    \"start:dev\": \"nest start --watc" +
                    "h\",\r\n    \"start:debug\": \"nest start --debug --watch\",\r\n    \"start:prod\": \"node d" +
                    "ist/main\",\r\n    \"lint\": \"eslint \\\"{src,apps,libs,test}/**/*.ts\\\" --fix\",\r\n    \"t" +
                    "est\": \"jest\",\r\n    \"test:watch\": \"jest --watch\",\r\n    \"test:cov\": \"jest --covera" +
                    "ge\",\r\n    \"test:debug\": \"node --inspect-brk -r tsconfig-paths/register -r ts-nod" +
                    "e/register node_modules/.bin/jest --runInBand\",\r\n    \"test:e2e\": \"jest --config " +
                    "./test/jest-e2e.json\"\r\n  },\r\n  \"dependencies\": {\r\n    \"@nestjs/common\": \"^8.0.0\"" +
                    ",\r\n    \"@nestjs/core\": \"^8.0.0\",\r\n    \"@nestjs/platform-express\": \"^8.0.0\",\r\n   " +
                    " \"@nestjs/swagger\": \"^6.1.2\",\r\n    \"reflect-metadata\": \"^0.1.13\",\r\n    \"rimraf\":" +
                    " \"^3.0.2\",\r\n    \"rxjs\": \"^7.2.0\",\r\n    \"uuid\": \"^9.0.0\"\r\n  },\r\n  \"devDependencie" +
                    "s\": {\r\n    \"@nestjs/cli\": \"^8.0.0\",\r\n    \"@nestjs/schematics\": \"^8.0.0\",\r\n    \"@" +
                    "nestjs/testing\": \"^8.0.0\",\r\n    \"@types/express\": \"^4.17.13\",\r\n    \"@types/jest\"" +
                    ": \"27.5.0\",\r\n    \"@types/node\": \"^16.0.0\",\r\n    \"@types/supertest\": \"^2.0.11\",\r\n" +
                    "    \"@typescript-eslint/eslint-plugin\": \"^5.0.0\",\r\n    \"@typescript-eslint/parse" +
                    "r\": \"^5.0.0\",\r\n    \"eslint\": \"^8.0.1\",\r\n    \"eslint-config-prettier\": \"^8.3.0\",\r" +
                    "\n    \"eslint-plugin-prettier\": \"^4.0.0\",\r\n    \"jest\": \"28.0.3\",\r\n    \"prettier\":" +
                    " \"^2.3.2\",\r\n    \"source-map-support\": \"^0.5.20\",\r\n    \"supertest\": \"^6.1.3\",\r\n  " +
                    "  \"ts-jest\": \"28.0.1\",\r\n    \"ts-loader\": \"^9.2.3\",\r\n    \"ts-node\": \"^10.0.0\",\r\n " +
                    "   \"tsconfig-paths\": \"4.0.0\",\r\n    \"typescript\": \"^4.3.5\"\r\n  },\r\n  \"jest\": {\r\n  " +
                    "  \"moduleFileExtensions\": [\r\n      \"js\",\r\n      \"json\",\r\n      \"ts\"\r\n    ],\r\n   " +
                    " \"rootDir\": \"src\",\r\n    \"testRegex\": \".*\\\\.spec\\\\.ts$\",\r\n    \"transform\": {\r\n   " +
                    "   \"^.+\\\\.(t|j)s$\": \"ts-jest\"\r\n    },\r\n    \"collectCoverageFrom\": [\r\n      \"**/*" +
                    ".(t|j)s\"\r\n    ],\r\n    \"coverageDirectory\": \"../coverage\",\r\n    \"testEnvironment\"" +
                    ": \"node\"\r\n  }\r\n}\r\n\r\n");
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        public override void Initialize() {
            base.Initialize();
        }
    }
}
