//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:5.0.17
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FullStackCodeGenerator {
    using SimpleCodeGenerator;
    using System;
    
    
    public partial class tsconfig_build_json_tt_daa09e2e_6526_4d99_993b_3e9de0e8a365 : BaseTemplate<ProjectTemplate> {
        
        
        #line 8 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Serverside\tsconfig.build.json.tt"

    public override string RelativeFilePath => $"Serverside/tsconfig.build.json";

        #line default
        #line hidden
        
        
        public override string TransformText() {
            this.GenerationEnvironment = null;
            
            #line 3 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Serverside\tsconfig.build.json.tt"
            this.Write("{\r\n    \"extends\": \"./tsconfig.json\",\r\n    \"exclude\": [\"node_modules\", \"test\", \"di" +
                    "st\", \"**/*spec.ts\"]\r\n}\r\n\r\n");
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        public override void Initialize() {
            base.Initialize();
        }
    }
}
