//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:5.0.17
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FullStackCodeGenerator {
    using SimpleCodeGenerator;
    using System;
    
    
    public partial class _EntityController_ts_tt_2942ff17_9fff_4eb6_9603_c5bb39eaed7f : BaseTemplate<EntityTemplate> {
        
        
        #line 32 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Serverside\src\Controllers\_EntityController.ts.tt"

    public override string RelativeFilePath => $"Serverside/src/Controllers/{Model.Entity.Name}Controller.ts";

        #line default
        #line hidden
        
        
        public override string TransformText() {
            this.GenerationEnvironment = null;
            
            #line 3 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Serverside\src\Controllers\_EntityController.ts.tt"
            this.Write("import { StorageProvider } from \'./../Services/StorageProvider\';\r\nimport { Body, " +
                    "Controller, Get, Post } from \'@nestjs/common\';\r\nimport { ");
            
            #line default
            #line hidden
            
            #line 5 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Serverside\src\Controllers\_EntityController.ts.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Model.Entity.Name ));
            
            #line default
            #line hidden
            
            #line 5 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Serverside\src\Controllers\_EntityController.ts.tt"
            this.Write(" } from \'src/Models/");
            
            #line default
            #line hidden
            
            #line 5 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Serverside\src\Controllers\_EntityController.ts.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Model.Entity.Name ));
            
            #line default
            #line hidden
            
            #line 5 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Serverside\src\Controllers\_EntityController.ts.tt"
            this.Write("\';\r\n\r\n@Controller(\'");
            
            #line default
            #line hidden
            
            #line 7 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Serverside\src\Controllers\_EntityController.ts.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Model.Entity.Name ));
            
            #line default
            #line hidden
            
            #line 7 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Serverside\src\Controllers\_EntityController.ts.tt"
            this.Write("\')\r\nexport class ");
            
            #line default
            #line hidden
            
            #line 8 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Serverside\src\Controllers\_EntityController.ts.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Model.Entity.Name ));
            
            #line default
            #line hidden
            
            #line 8 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Serverside\src\Controllers\_EntityController.ts.tt"
            this.Write("Controller {\r\n  constructor(private readonly storageProvider: StorageProvider) {}" +
                    "\r\n\r\n  @Post(\'create\')\r\n  create(@Body() entity: ");
            
            #line default
            #line hidden
            
            #line 12 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Serverside\src\Controllers\_EntityController.ts.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Model.Entity.Name ));
            
            #line default
            #line hidden
            
            #line 12 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Serverside\src\Controllers\_EntityController.ts.tt"
            this.Write("): ");
            
            #line default
            #line hidden
            
            #line 12 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Serverside\src\Controllers\_EntityController.ts.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Model.Entity.Name ));
            
            #line default
            #line hidden
            
            #line 12 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Serverside\src\Controllers\_EntityController.ts.tt"
            this.Write(" {\r\n    return this.storageProvider.Create(entity, \'");
            
            #line default
            #line hidden
            
            #line 13 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Serverside\src\Controllers\_EntityController.ts.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Model.Entity.Name ));
            
            #line default
            #line hidden
            
            #line 13 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Serverside\src\Controllers\_EntityController.ts.tt"
            this.Write("\');\r\n  }\r\n\r\n  @Get(\'read\')\r\n  read(): Array<");
            
            #line default
            #line hidden
            
            #line 17 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Serverside\src\Controllers\_EntityController.ts.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Model.Entity.Name ));
            
            #line default
            #line hidden
            
            #line 17 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Serverside\src\Controllers\_EntityController.ts.tt"
            this.Write("> {\r\n    return this.storageProvider.Read(\'");
            
            #line default
            #line hidden
            
            #line 18 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Serverside\src\Controllers\_EntityController.ts.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Model.Entity.Name ));
            
            #line default
            #line hidden
            
            #line 18 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Serverside\src\Controllers\_EntityController.ts.tt"
            this.Write("\');\r\n  }\r\n\r\n  @Post(\'update\')\r\n  update(@Body() entity: ");
            
            #line default
            #line hidden
            
            #line 22 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Serverside\src\Controllers\_EntityController.ts.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Model.Entity.Name ));
            
            #line default
            #line hidden
            
            #line 22 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Serverside\src\Controllers\_EntityController.ts.tt"
            this.Write("): ");
            
            #line default
            #line hidden
            
            #line 22 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Serverside\src\Controllers\_EntityController.ts.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Model.Entity.Name ));
            
            #line default
            #line hidden
            
            #line 22 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Serverside\src\Controllers\_EntityController.ts.tt"
            this.Write(" {\r\n    return this.storageProvider.Update(entity, \'");
            
            #line default
            #line hidden
            
            #line 23 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Serverside\src\Controllers\_EntityController.ts.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Model.Entity.Name ));
            
            #line default
            #line hidden
            
            #line 23 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Serverside\src\Controllers\_EntityController.ts.tt"
            this.Write("\');\r\n  }\r\n\r\n  @Post(\'delete\')\r\n  delete(@Body() entity: ");
            
            #line default
            #line hidden
            
            #line 27 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Serverside\src\Controllers\_EntityController.ts.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Model.Entity.Name ));
            
            #line default
            #line hidden
            
            #line 27 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Serverside\src\Controllers\_EntityController.ts.tt"
            this.Write("): ");
            
            #line default
            #line hidden
            
            #line 27 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Serverside\src\Controllers\_EntityController.ts.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Model.Entity.Name ));
            
            #line default
            #line hidden
            
            #line 27 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Serverside\src\Controllers\_EntityController.ts.tt"
            this.Write(" {\r\n    return this.storageProvider.Delete(entity, \'");
            
            #line default
            #line hidden
            
            #line 28 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Serverside\src\Controllers\_EntityController.ts.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Model.Entity.Name ));
            
            #line default
            #line hidden
            
            #line 28 "P:\CodeGeneratorDemos\SimpleCodeGenerator\FullStackCodeGenerator\MDE\Templates\Serverside\src\Controllers\_EntityController.ts.tt"
            this.Write("\');\r\n  }\r\n}\r\n\r\n");
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        public override void Initialize() {
            base.Initialize();
        }
    }
}
